# Custom data for person detection


# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
train: datasets/images/
val: datasets/images/
test: datasets/test/images
# number of classes
nc: 1

# class names
names: ['crack']
